Add module decidim-awesome
diputacioBCN/decidim-diba pull request #111
Opened 2022-03-01 10:02 UTC by LauraJaimeC

Info: https://github.com/Platoniq/decidim-module-decidim_awesome#installation

2022-03-01 15:29 UTC, tramuntanal requested changes
There's a question about forcing the desired awesome version.

Also, can you add a check in `spec/features/remove_overrides_spec.rb` because I think we will have to do somethinkg when upgrading to Decidim v0.25?

2022-03-01 15:29 UTC, tramuntanal commented on Gemfile
> +gem "decidim-decidim_awesome"
No need to force version?

2022-03-01 15:46 UTC, LauraJaimeC commented on Gemfile
> +gem "decidim-decidim_awesome"
Yes, we can force to 0.7.2 version!

2022-03-02 11:25 UTC, tramuntanal approved these changes

2022-03-07 10:54 UTC, merged