New users segmentation in newsletters
diputacioBCN/decidim-diba pull request #128
Opened 2023-10-06 14:12 UTC by laurajaime

2023-10-18 05:56 UTC, tramuntanal requested changes
Great work here @laurajaime ! :clap: 

I've left some User scoping related comments and some other small things.

2023-10-18 05:56 UTC, tramuntanal commented on app/overrides/decidim/admins/newsletter/select_recipients_to_deliver.rb
> +Deface::Override.new(virtual_path: "decidim/admin/newsletters/select_recipients_to_deliver",
Can you add the hash of the original file?

2023-10-18 05:56 UTC, tramuntanal commented on app/views/decidim/admin/newsletters/_select_single_users.html.erb
> +              Decidim::User.all.map{ |user| ["#{user.name} (#{user.email})", user.id] },
Only users from current Organization

2023-10-18 05:56 UTC, tramuntanal commented on config/locales/ca.yml
> +          send_to_selected_users: Enviar als usuaris seleccionats
```suggestion
          send_to_selected_users: Envia als usuaris seleccionats
```

2023-10-18 05:56 UTC, tramuntanal commented on .rubocop_ruby.yml
> +  Max: 40
we can change to 10 but 40 is way too much

2023-10-18 05:56 UTC, tramuntanal commented on .rubocop_ruby.yml
> +  Max: 40
Don't change please

2023-10-18 05:56 UTC, tramuntanal commented on .rubocop_ruby.yml
> +  Max: 35
Please, disable if needed but don't change the default

2023-10-18 05:56 UTC, tramuntanal commented on app/controllers/newsletter_settings_controller.rb
> +    user = Decidim::User.find(params[:user_id])
Filter by current Organization

2023-10-18 05:56 UTC, tramuntanal commented on app/decorators/queries/admin/newsletter_recipients_decorator.rb
> +        Decidim::User.where(id: @form.selected_users_ids)
Filter by current Organization

2023-10-18 19:57 UTC, laurajaime commented on app/controllers/newsletter_settings_controller.rb
> +    user = Decidim::User.find(params[:user_id])
wow...thanks!!!

2023-10-19 07:06 UTC, tramuntanal commented on .rubocop_ruby.yml
> +  Max: 35
I meant to disable on each place it raises, not to disable the Cop

2023-10-19 07:09 UTC, tramuntanal approved these changes
Ok

2023-10-23 09:57 UTC, merged